displayName=Bingo Loot Logger
author=Marnkie
description=Logs custom bingo loot to a discord webhook.
tags=bingo,loot,logger,discord
version=
plugins=com.bingolootlogger.BingoLootLoggerPlugin
build=standard